---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-ebs-dynamic-pvc
  namespace: roboshop
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: "roboshop-ebs-sc"
