apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-set
  namespace: roboshop
  labels:
    app: redis
    tier: db
    project: roboshop
spec:
  selector:
    matchLabels:
      app: redis
      tier: db
      project: roboshop     # has to match .spec.template.metadata.labels

  serviceName: "redis-service"
  replicas: 1               # by default is 1
  template:
    metadata:
      labels:
        app: redis
        tier: db
        project: roboshop   # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: redis
        image: redis
        volumeMounts:
        - name: redis-pv
          mountPath: /data
      volumes:
      - name: redis-pv
        persistentVolumeClaim:
          claimName: redis-ebs-dynamic-pvc