---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
  namespace: ecommerce
data:
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  MYSQL_DATABASE: "cities"
  MYSQL_USER: "shipping"
  MYSQL_PASSWORD: "Roboshop@1"
