---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-ebs-dynamic-pvc
  namespace: ecommerce
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: "ecommerce-ebs-sc"
