apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-set
  namespace: roboshop
  labels:
    app: mysql
    tier: db
    project: roboshop
spec:
  selector:
    matchLabels:
      app: mysql
      tier: db
      project: roboshop     # has to match .spec.template.metadata.labels

  serviceName: "mysql-service"
  replicas: 1               # by default is 1
  template:
    metadata:
      labels:
        app: mysql
        tier: db
        project: roboshop   # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: mysql
        image: "dockerjackal/mysql:{{ .Values.statefulset.imageVersion }}"
        envFrom:
        - configMapRef:
            name: mysql-configmap
        volumeMounts:
        - name: mysql-pv
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-pv
        persistentVolumeClaim:
          claimName: mysql-ebs-dynamic-pvc