apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: ecommerce
  labels: 
    app: user
    project: ecommerce
    tier: app
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: user
      project: ecommerce
      tier: app
  template:
    metadata:
      labels:
        app: user
        project: ecommerce
        tier: app
    spec:
      containers:
      - name: user
        image: "dockerjackal/user:{{ .Values.deployment.imageVersion }}"
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: user-config
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"
        imagePullPolicy: Always
