apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ecommerce-sc
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce