#!groovy

// it means libraries will be downloaded and accessible at run time
@Library('roboshop-library') _
// nodeJs_CI

def configMap = [
   // application: "nodejsVM",
    application: "nodejsEKS",   // now we are migrating from monolithic to microservice
    component: "user"
]

// this is .groovy file name with a function call and map as a parameter
// if not master, then trigger the pipeline using webhooks
if (! env.BRANCH_NAME.equals('master')){
    pipelineDecision.decidePipeline(configMap)
}
else{
    echo "Master PROD Deployment should happen through CR (Change Request)"
}
   
 

