#=====================================================================================
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: ecommerce
  labels: # these labels are deployment labels
    app: catalogue
    tier: db
    project: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels: # these labels are used to find the pods
      app: catalogue
      tier: db
      project: ecommerce
  template:
    metadata:
      labels: # these labels are pod labels
        app: catalogue
        tier: db
        project: ecommerce
    spec:
      containers:
      - name: catalogue
        image: "dockerjackal/catalogue:{{ .Values.deployment.imageVersion }}"
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: catalogue-config
