
apiVersion: v1
kind: Service
metadata:
  name: catalogue-service
  namespace: ecommerce
spec:
  selector:
    app: catalogue
    tier: db
    project: ecommerce
  ports:
  - name: catalogue-port
    protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #container-port
