
apiVersion: v1
kind: Service
metadata:
  name: catalogue-service
  namespace: roboshop
spec:
  selector:
    app: catalogue
    project: roboshop
    tier: app
  ports:
  - name: catalogue-port
    protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #container-port
