apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ecommerce-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce