---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: roboshop
spec:
  clusterIP: None       # headless service
  selector:
    app: rabbitmq
    tier: db
    project: roboshop
  ports:
  - name: rabbitmq-service-port
    protocol: TCP
    port: 5672           # this port no belongs to service
    targetPort: 5672     # this port belongs to container