apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq-set
  labels:
    app: rabbitmq
    tier: db
    project: roboshop
spec:
  selector:
    matchLabels:
      app: rabbitmq
      tier: db
      project: roboshop     # has to match .spec.template.metadata.labels

  serviceName: "rabbitmq-service"
  replicas: 1               # by default is 1
  template:
    metadata:
      labels:
        app: rabbitmq
        tier: db
        project: roboshop   # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq
        volumeMounts:
        - name: rabbitmq-pv
          mountPath: /var/lib/rabbitmq
      volumes:
      - name: rabbitmq-pv
        persistentVolumeClaim:
          claimName: rabbitmq-ebs-dynamic-pvc