---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: ecommerce
spec:
  clusterIP: None       # headless service
  selector:
    app: redis
    tier: db
    project: ecommerce 
  ports:
  - name: redis-service-port
    protocol: TCP
    port: 6379            # this port no belongs to service
    targetPort: 6379      # this port belongs to container