---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: ecommerce
spec:
  clusterIP: None       # headless service
  selector:
    app: mysql
    tier: db
    project: ecommerce 
  ports:
  - name: mysql-service-port
    protocol: TCP
    port: 3306            # this port no belongs to service
    targetPort: 3306      # this port belongs to container