apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: ecommerce
  labels:
    app: mysql
    project: ecommerce
    tier: db
spec:
  clusterIP: None
  selector:
    app: mongodb
    project: ecommerce
    tier: db
  ports:
  - protocol: TCP
    port: 3306            
    targetPort: 3306
