---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: ecommerce
  labels:
    app: mysql
    project: ecommerce
    tier: db
spec:
  clusterIP: None       # headless service
  selector:
    app: mysql
    project: ecommerce
    tier: db
  ports:
    protocol: TCP
    port: 3306            # this port no belongs to service
    targetPort: 3306      # this port belongs to container