apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: ecommerce
  labels:
    app: mysql
    project: ecommerce
    tier: db
spec:
  selector:
    matchLabels:
      app: mysql
      project: ecommerce
      tier: db
  serviceName: "mysql"
  replicas: {{ .Values.statefulset.replicas }}
  template:
    metadata:
      labels:
        app: mysql
        project: ecommerce
        tier: db
    spec:
      containers:
      - name: mysql
        image: "dockerjackal/mysql:{{ .Values.statefulset.imageVersion }}"
        envFrom:
        - configMapRef:
            name: mysql-configmap
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
    volumeClaimTemplates:
    - metadata:
        name: mysql
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "ecommerce-sc"
        resources:
          requests:
            storage: 1Gi