apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: ecommerce
  labels: 
    app: shipping
    project: ecommerce
    tier: app
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: shipping
      project: ecommerce
      tier: app
  template:
    metadata:
      labels:
        app: shipping
        project: ecommerce
        tier: app
    spec:
      containers:
      - name: shipping
        image: "dockerjackal/shipping:{{ .Values.deployment.imageVersion }}"
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: shipping-config
        resources:
          requests:
            cpu: "150m"
            memory: "256Mi"
          limits:
            cpu: "300m"
            memory: "512Mi"
        imagePullPolicy: Always
