apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: ecommerce
  labels:
    app: rabbitmq
    project: ecommerce
    tier: db
spec:
  selector:
    matchLabels:
      app: rabbitmq
      project: ecommerce
      tier: db 
  serviceName: "rabbitmq"
  replicas: {{ .Values.statefulset.replicas }}
  template:
    metadata:
      labels:
        app: rabbitmq
        project: ecommerce
        tier: db 
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq
        envFrom:
        - secretRef:
            name: rabbitmq-secret
        volumeMounts:
        - name: rabbitmq
          mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ecommerce-sc"
      resources:
        requests:
          storage: 1Gi