---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: ecommerce
spec:
  storageClassName: "ecommerce-ebs-sc"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  
