apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: ecommerce
  labels:
    app: mongodb
    project: ecommerce
    tier: db
spec:
  ports:
  - protocol: TCP
    port: 27017 #service-port
    targetPort: 27017
  clusterIP: None
  selector:
    app: mongodb
    project: ecommerce
    tier: db