apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: ecommerce
  labels:
    app: mongodb
    project: ecommerce
    tier: db
spec:
  selector:
    matchLabels:
      app: mongodb
      project: ecommerce
      tier: db
  serviceName: "mongodb"
  replicas: {{ .Values.statefulset.replicas }}
  template:
    metadata:
      labels:
        app: mongodb
        project: ecommerce
        tier: db
    spec:
      containers:
      - name: mongodb
        image: "dockerjackal/mongodb:{{ .Values.statefulset.imageVersion }}"
        volumeMounts:
        - name: mongodb
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ecommerce-sc"
      resources:
        requests:
          storage: 1Gi