---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: ecommerce
  labels:
    app: rabbitmq
    project: ecommerce
    tier: db
spec:
  clusterIP: None       # headless service
  selector:
    app: rabbitmq
    project: ecommerce
    tier: db
  ports:
  - protocol: TCP
    port: 5672           # this port no belongs to service
    targetPort: 5672     # this port belongs to container