#=====================================================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-config
  namespace: ecommerce
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"