
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: ecommerce
spec:
  selector:
    app: cart
    project: ecommerce
    tier: app
  ports:
  - protocol: TCP
    port: 8080          #service-port
    targetPort: 8080    #container-port
