---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ecommerce
  region: us-east-1

managedNodeGroups:                                      # Completely Managed by AWS
  - name: ecommerce
    instanceType: t2.micro
    desiredCapacity: 3                                  # Your nodes can be takes back at any point of time
    volumeSize: 20
    ssh:
      publicKeyName: Virginia-KeyPair                   # Your Key pair in AWS